### ISSUE TITLE
Consider allowing DV_TEXT 'object', even if only a value attribute is present

### ISSUE THREAD

**Issue by freshehr** [better-care/web-template#5]
For DV_TEXT, if the data is {comment: "some Text"} , currently {comment: {value: "some text"}} is not valid when committing data, only {comment: "some text"}.

This makes handling constraints where both text and codedText are valid, more awkward since it should be possible to infer text from codedText by the presence/absence of terminology and code attributes.

**Comment by delopst** [comment]
Hi.

This is already possible but the syntax of the value attribute is inccorect.

{"comment": "some Text"}
{"comment": {"|value": "some text"}}

Regards, Primož

**Comment by freshehr** [comment]
Ah yes thanks. I was sure {"comment": {"|value": "some text"}} was rejected in the past - perhaps it has been fixed.

**Comment by delopst** [comment]
I have tried this before answering you :) 

Can I close this issue or do you want to try this before closing?

Regards, Primož

**Comment by freshehr** [comment]
Confirmed it works - closing
